#Site settings

title:
  en: "Chitra Santhe - ART FOR ALL"
  kn: "ಚಿತ್ರಸಂತೆ - ಎಲ್ಲರಿಗಾಗಿ ಕಲೆ"

owner:
  en: "Karnataka Chitrakala Parishath"
  kn: "ಕರ್ನಾಟಕ ಚಿತ್ರಕಲಾ ಪರಿಷತ್"

index:
  en: en
  kn: ಕನ್ನಡ

arts:
  en: arts
  kn: ಕಲೆಗಳು

artists:
  en: artists
  kn: ಕಲಾವಿದರು

description:
  en: "A 17th successive annual event/ fair being organised by Karnataka Chitrakala Parishath, Bengaluru."
  kn: "A 17th successive annual event/ fair being organised by Karnataka Chitrakala Parishath, Bengaluru."

logo:
  en: "cse.png"
  kn: "csk.png"

email: chitrakalaparishath@gmail.com

baseurl: ""
url: "https://chitrasanthe.org"
twitter_username: chitrasanthe
github_username: chitrasanthe

# Build settings
theme: minima

# plugins:
#   - jekyll-feed

include: ["_pages"]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true

sass:
  sass_dir: _scss
  style: compressed
